### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [Shirakumo/3d-spaces#7]
Building with SBCL 2.3.6.173-55d27b14b / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 781aaa045ba6c140ec720d1d6c39e834aa0675c9

*3d-spaces-test* fails to build with the following error:

```
Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD tid=2856564 "main thread" RUNNING {1001710003}>: no symbol named "ENSURE-FUNCTION" in "ORG.SHIRAKUMO.FRAF.TRIAL.SPACE"

```

*3d-spaces* fails to build with the following error:

```
Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD tid=2856568 "main thread" RUNNING {1001710003}>: no symbol named "ENSURE-FUNCTION" in "ORG.SHIRAKUMO.FRAF.TRIAL.SPACE"

```

[Full log here](http://report.quicklisp.org/2023-09-27/failure-report/3d-spaces.html)

**Comment by quicklisp** [comment]
Now that's service!

**Comment by Shinmera** [comment]
🫡
